// Generated by CoffeeScript 1.7.0
(function() {
  $(document).ready(function() {
    $('.our-tours, .sub').mouseenter(function() {
      $('.sub').slideDown();
      return $(this).addClass('active');
    });
    return $('header nav').mouseleave(function() {
      return setTimeout(function() {
        $('.sub').slideUp();
        return $('.our-tours').removeClass('active');
      }, 400);
    });
  });

}).call(this);
