// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    $('.our-tours, .sub').mouseenter(function() {
      $('.sub').slideDown();
      return $(this).addClass('active');
    });
    return $('nav').mouseleave(function() {
      return setTimeout(function() {
        $('.sub').slideUp();
        return $('.our-tours').removeClass('active');
      }, 1000);
    });
  });

}).call(this);
